name: Labeling new issue

on:
  issues:
      types: ['opened', 'edited']

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/auto-label.json5

      - uses: Renato66/auto-label@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
